<table align="center" bgcolor="#444" width="800px">
                                <tr><form action="manage.php" method="post">
                                    <td align="left" width="100px" >
                                        <span align="center" style='padding:20px; font-weight:bolder'>Add</span>
                                        <br/>
                                        <x align="center"><input type="submit" name="add" value="Music" style="margin-left:20px; width:100%; cursor:pointer; border:thin #555 solid; background-color:#555; color:#CCC; padding:10px"/></x><br/>
                                        <x align="center"><input type="submit" name="add" value="Person" style="margin-left:20px; width:100%; cursor:pointer; border:thin #555 solid; background-color:#555; color:#CCC; padding:10px"/></x><br/>
                                        <x align="center"><input type="submit" name="add" value="Label" style="margin-left:20px; width:100%; cursor:pointer; border:thin #555 solid; background-color:#555; color:#CCC; padding:10px"/></x><br/>
                                        <x align="center"><input type="submit" name="add" value="Activity" style="margin-left:20px; width:100%; cursor:pointer; border:thin #555 solid; background-color:#555; color:#CCC; padding:10px"/></x>
                                    </td><td align="left" width="100px" >
                                        <span align="center" style='padding:20px; font-weight:bolder'>Delete</span>
                                        <br/>
                                        <x align="center"><input type="submit" name="delete" value="Music" style="margin-left:20px; width:90%; cursor:pointer; border:thin rgb(180,100,100) solid; background-color:#555; color:#CCC; padding:10px"/></x><br/>
                                        <x align="center"><input type="submit" name="delete" value="Person" style="margin-left:20px; width:90%; cursor:pointer; border:thin rgb(180,100,100) solid; background-color:#555; color:#CCC; padding:10px"/></x><br/>
                                        <x align="center"><input type="submit" name="delete" value="Label" style="margin-left:20px; width:90%; cursor:pointer; border:thin rgb(180,100,100) solid; background-color:#555; color:#CCC; padding:10px"/></x><br/>
                                        <x align="center"><input type="submit" name="delete" value="Activity" style="margin-left:20px; width:90%; cursor:pointer; border:thin rgb(180,100,100) solid; background-color:#555; color:#CCC; padding:10px"/></x>
                                    </td></form>
                                    </tr>
                        </table>